# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Docker Setup QEMU with Local Cache'
description: 'Install QEMU static binaries'
author: 'docker'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  image:
    description: 'QEMU static binaries Docker image (e.g. tonistiigi/binfmt:latest)'
    default: 'docker.io/tonistiigi/binfmt:latest'
    required: false
  platforms:
    description: 'Platforms to install (e.g. arm64,riscv64,arm)'
    default: 'all'
    required: false
  cache-image:
    description: 'Cache binfmt image to GitHub Actions cache backend'
    default: 'true'
    required: false
  cache-image-path:
    description: >
      Local path to store the binfmt image. Using this enables local caching instead of GitHub Actions cache.
      Note: The "latest" tag won't auto-update - delete the cached file to fetch updates.
    default: ''
    required: false

outputs:
  platforms:
    description: 'Available platforms (comma separated)'

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
