name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:


# on:
#   schedule:
#     - cron: '0 10 * * *'
#   push:
#     branches:
#       - 'master'
#       - 'releases/v*'
#     tags:
#       - 'v*'
#   pull_request:

jobs:
  default:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        cache-image-path:
          - /tmp/cache

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        id: qemu
        uses: ./
        with:
          cache-image-path: ${{ matrix.cache-image-path }}
      -
        name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
