name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: self-hosted
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Publish
        uses: actions/publish-immutable-action@v0.0.4
